name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
permissions:
  write-all
jobs:

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Typecheck
        run: nr typecheck

  build:
    needs: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: icalingua-theme-telegram.zip
          path: dist
      - name: Zip
        run: zip -r icalingua-theme-telegram.zip dist
      - name: Upload a Build Artifact
        if: github.ref == 'refs/heads/main'
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/wibus-wee/icalingua-theme-telegram/releases/111083577/assets{?name,label}
          release_id: 111083577
          asset_path: ./icalingua-theme-telegram.zip
          asset_name: icalingua-theme-telegram-$$.zip
          asset_content_type: application/zip
          max_releases: 7